export const distritosLima = [
  { label: 'Ancón', value: 'Ancón' },
  { label: 'Ate', value: 'Ate' },
  { label: 'Barranco', value: 'Barranco' },
  { label: 'Bellavista', value: 'Bellavista' },
  { label: 'Breña', value: 'Breña' },
  { label: 'Callao', value: 'Callao' },
  { label: 'Carmen de la Legua Reynoso', value: 'Carmen de la Legua Reynoso' },
  { label: 'Carabayllo', value: 'Carabayllo' },
  { label: 'Cercado de Lima', value: 'Cercado de Lima' },
  { label: 'Chaclacayo', value: 'Chaclacayo' },
  { label: 'Chorrillos', value: 'Chorrillos' },
  { label: 'Cieneguilla', value: 'Cieneguilla' },
  { label: 'Comas', value: 'Comas' },
  { label: 'El Agustino', value: 'El Agustino' },
  { label: 'Independencia', value: 'Independencia' },
  { label: 'Jesús María', value: 'Jesús María' },
  { label: 'La Molina', value: 'La Molina' },
  { label: 'La Perla', value: 'La Perla' },
  { label: 'La Punta', value: 'La Punta' },
  { label: 'La Victoria', value: 'La Victoria' },
  { label: 'Lince', value: 'Lince' },
  { label: 'Los Olivos', value: 'Los Olivos' },
  { label: 'Lurín', value: 'Lurín' },
  { label: 'Lurigancho', value: 'Lurigancho' },
  { label: 'Magdalena del Mar', value: 'Magdalena del Mar' },
  { label: 'Miraflores', value: 'Miraflores' },
  { label: 'Pachacámac', value: 'Pachacámac' },
  { label: 'Pucusana', value: 'Pucusana' },
  { label: 'Pueblo Libre', value: 'Pueblo Libre' },
  { label: 'Puente Piedra', value: 'Puente Piedra' },
  { label: 'Punta Hermosa', value: 'Punta Hermosa' },
  { label: 'Punta Negra', value: 'Punta Negra' },
  { label: 'Rímac', value: 'Rímac' },
  { label: 'San Bartolo', value: 'San Bartolo' },
  { label: 'San Borja', value: 'San Borja' },
  { label: 'San Isidro', value: 'San Isidro' },
  { label: 'San Juan de Lurigancho', value: 'San Juan de Lurigancho' },
  { label: 'San Juan de Miraflores', value: 'San Juan de Miraflores' },
  { label: 'San Luis', value: 'San Luis' },
  { label: 'San Martín de Porres', value: 'San Martín de Porres' },
  { label: 'San Miguel', value: 'San Miguel' },
  { label: 'Santa Anita', value: 'Santa Anita' },
  { label: 'Santa María del Mar', value: 'Santa María del Mar' },
  { label: 'Santa Rosa', value: 'Santa Rosa' },
  { label: 'Santiago de Surco', value: 'Santiago de Surco' },
  { label: 'Surquillo', value: 'Surquillo' },
  { label: 'Ventanilla', value: 'Ventanilla' },
  { label: 'Villa El Salvador', value: 'Villa El Salvador' },
  { label: 'Villa María del Triunfo', value: 'Villa María del Triunfo' }
]


export const getDistritoLabel = (value) => {
  const distrito = distritosLima.find(d => d.value === value)
  return distrito ? distrito.label : ''
}
